# Generated by Django 2.1.2 on 2019-03-26 18:30

import apps.iiif.canvases.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manifests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('pid', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='IServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('IIIF_IMAGE_SERVER_BASE', models.CharField(default=apps.iiif.canvases.models.get_default_iiif_setting, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='canvas',
            name='IIIF_IMAGE_SERVER_BASE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvases.IServer'),
        ),
        migrations.AddField(
            model_name='canvas',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manifests.Manifest'),
        ),
    ]
