# Generated by Django 2.1.2 on 2018-11-01 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('pid', models.CharField(max_length=255)),
                ('summary', models.TextField()),
            ],
        ),
    ]
