# Generated by Django 2.1.2 on 2018-12-17 22:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manifests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('pid', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('position', models.IntegerField()),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manifests.Manifest')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
