# Generated by Django 2.1.2 on 2018-11-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canvases', '0001_initial'),
        ('manifests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manifests.Manifest'),
        ),
    ]
