# Generated by Django 2.1.2 on 2019-03-14 19:25

import apps.iiif.canvases.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IServer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('IIIF_IMAGE_SERVER_BASE', models.CharField(default=apps.iiif.canvases.models.get_default_iiif_setting, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='canvas',
            name='IIIF_IMAGE_SERVER_BASE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvases.IServer'),
        ),
    ]
