# Generated by Django 2.1.2 on 2019-04-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='is_starting_page',
            field=models.BooleanField(default=False),
        ),
    ]
