# Generated by Django 2.1.2 on 2018-11-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0002_canvas_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
