# Generated by Django 2.1.2 on 2019-09-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0002_canvas_is_starting_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='default_ocr',
            field=models.CharField(choices=[('word', 'word'), ('line', 'line'), ('both', 'both')], default='word', max_length=30),
        ),
    ]
