# Generated by Django 2.2.10 on 2020-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0003_canvas_default_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='ocr_offset',
            field=models.IntegerField(default=0),
        ),
    ]
