# Generated by Django 2.1.2 on 2018-11-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0003_canvas_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvas',
            options={'ordering': ['position']},
        ),
    ]
