# Generated by Django 2.2.10 on 2020-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0004_canvas_ocr_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='iserver',
            name='storage_path',
            field=models.CharField(default='readux', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iserver',
            name='storage_service',
            field=models.CharField(choices=[('sftp', 'SFTP'), ('s3', 'S3')], default='sftp', max_length=10),
        ),
    ]
