# Generated by Django 2.1.2 on 2018-11-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0004_auto_20181102_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='canvas',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
