# Generated by Django 2.2.10 on 2021-01-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_auto_20210119_1936'),
        ('canvases', '0006_canvas_ocr_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvas',
            name='IIIF_IMAGE_SERVER_BASE',
        ),
        migrations.DeleteModel(
            name='IServer',
        ),
    ]
