# Generated by Django 2.2.10 on 2021-03-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0007_auto_20210107_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='resource',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='ocr_file_path',
            field=models.FilePathField(allow_folders=True, blank=True, null=True, path='/tmp', recursive=True),
        ),
    ]
