# Generated by Django 2.2.23 on 2021-08-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0008_auto_20210309_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='ocr_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
