# Generated by Django 2.2.10 on 2021-06-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0008_auto_20210309_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvas',
            name='IIIF_IMAGE_SERVER_BASE',
        ),
        migrations.AlterField(
            model_name='canvas',
            name='ocr_file_path',
            field=models.FilePathField(allow_folders=True, blank=True, null=True, path='/var/folders/6q/m6_cn6w96g158vldpfhnn6k40000gn/T', recursive=True),
        ),
        migrations.DeleteModel(
            name='IServer',
        ),
    ]
