# Generated by Django 2.2.23 on 2021-09-28 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0021_auto_20210928_1301'),
        ('canvases', '0009_auto_20210819_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='image_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manifests.ImageServer'),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='pid',
            field=models.CharField(default='2qkkkqds', help_text="Unique ID. Do not use -'s or spaces in the pid.", max_length=255),
        )
    ]
