# Generated by Django 2.2.23 on 2021-09-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0009_auto_20210819_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvas',
            name='IIIF_IMAGE_SERVER_BASE',
        ),
        migrations.RemoveField(
            model_name='iserver',
            name='storage_path',
        ),
        migrations.RemoveField(
            model_name='iserver',
            name='storage_service',
        ),
    ]
