# Generated by Django 2.2.24 on 2022-02-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0017_auto_20220113_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='pid',
            field=models.CharField(default='2r42twcf', help_text="Unique ID. Do not use _'s or spaces in the pid.", max_length=255),
        ),
    ]
