# Generated by Django 3.2.15 on 2023-02-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0027_auto_20220607_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='label',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
