# Generated by Django 2.2.1 on 2019-07-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_auto_20190715_2021'),
        ('readux', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userannotation',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='userannotation',
            name='end_offset',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userannotation',
            name='end_selector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_selector', to='annotations.Annotation'),
        ),
        migrations.AddField(
            model_name='userannotation',
            name='start_offset',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userannotation',
            name='start_selector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_selector', to='annotations.Annotation'),
        ),
    ]
