# Generated by Django 2.1.2 on 2019-10-02 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readux', '0002_auto_20190920_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userannotation',
            name='end_offset',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='end_selector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_selector', to='annotations.Annotation'),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='start_offset',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='start_selector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_selector', to='annotations.Annotation'),
        ),
    ]
