# Generated by Django 2.1.2 on 2019-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readux', '0003_auto_20191002_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userannotation',
            name='style',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
