# Generated by Django 2.1.2 on 2020-01-30 17:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('readux', '0004_userannotation_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='userannotation',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
