# Generated by Django 2.1.2 on 2020-01-30 17:24

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('readux', '0005_userannotation_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedUserAnnotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='readux.TaggedUserAnnotations', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='taggeduserannotations',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readux.UserAnnotation'),
        ),
        migrations.AddField(
            model_name='taggeduserannotations',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readux_taggeduserannotations_items', to='taggit.Tag'),
        ),
    ]
