# Generated by Django 2.2.10 on 2020-12-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readux', '0006_auto_20200130_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userannotation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
