# Generated by Django 2.2.10 on 2020-05-08 15:56

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('readux', '0006_auto_20200130_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=255)),
                ('socialmediaicon', models.ImageField(help_text='Upload your site social media icon.', null=True, upload_to='icons/')),
                ('sitelogo', models.FileField(default='/Users/joanna/Documents/Readux_dev/readux/staticfiles/images/readux.svg', help_text='Upload the site logo in svg (png or jpg accepted).', null=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])])),
            ],
        ),
    ]
