# Generated by Django 2.2.10 on 2020-05-08 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readux', '0007_siteinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinformation',
            options={'verbose_name_plural': 'Site information'},
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='sitelogo',
            field=models.FileField(default='../static/images/readux.svg', help_text='Leave blank for Readux logo or upload your site logo in svg (png or jpg accepted).', null=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])], verbose_name='Site logo'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='sitename',
            field=models.CharField(max_length=255, verbose_name='site name'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='socialmediaicon',
            field=models.ImageField(help_text='Upload your site social media icon.', null=True, upload_to='icons/', verbose_name='social media icon'),
        ),
    ]
