# Generated by Django 3.2.13 on 2022-06-07 14:07

from django.db import migrations, models
from apps.iiif.annotations.choices import AnnotationSelector

def assign_selector(apps, _):
    Annotation = apps.get_model("readux", "UserAnnotation")  # pylint: disable=invalid-name
    for anno in Annotation.objects.all():
        if anno.svg:
            anno.primary_selector = AnnotationSelector('SV')


class Migration(migrations.Migration):

    dependencies = [
        ('readux', '0008_auto_20210309_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userannotation',
            name='primary_selector',
            field=models.CharField(choices=[('FR', 'FragmentSelector'), ('CS', 'CssSelector'), ('XP', 'XPathSelector'), ('TQ', 'TextQuoteSelector'), ('TP', 'TextPositionSelector'), ('DP', 'DataPositionSelector'), ('SV', 'SvgSelector'), ('RG', 'RangeSelector')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='userannotation',
            name='purpose',
            field=models.CharField(choices=[('AS', 'assessing'), ('BM', 'bookmarking'), ('CL', 'classifying'), ('CM', 'commenting'), ('DS', 'describing'), ('ED', 'editing'), ('HL', 'highlighting'), ('ID', 'identifying'), ('LK', 'linking'), ('MO', 'moderating'), ('QT', 'questioning'), ('RE', 'replying'), ('TG', 'tagging')], default='CM', max_length=2),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='w',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(assign_selector, migrations.RunPython.noop),
 ]
