# Generated by Django 2.2.10 on 2021-06-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readux', '0009_userannotationgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userannotation',
            options={'permissions': (('can_view', 'Can view annotations'), ('can_edit', 'Can edit annotations'), ('can_delete', 'Can delete annotations'))},
        ),
    ]
