# Generated by Django 2.2.10 on 2021-06-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readux', '0010_auto_20210618_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userannotation',
            options={'permissions': (('can_view', 'Can view shared annotations'), ('can_edit', 'Can edit shared annotations'), ('can_delete', 'Can delete shared annotations'))},
        ),
    ]
