# Generated by Django 2.2.10 on 2021-06-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readux', '0012_auto_20210618_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userannotation',
            options={'permissions': (('view_user_annotation', 'View annotation'), ('admin_annotation', 'Manage annotation'))},
        ),
    ]
