# Generated by Django 4.2.30 on 2026-05-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('readux', '0012_userannotation_raw_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeduserannotations',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='motivation',
            field=models.CharField(choices=[('oa:commenting', 'commenting'), ('sc:painting', 'painting'), ('supplementing', 'supplementing')], default='sc:painting', max_length=50),
        ),
    ]
