# Generated by Django 2.1.2 on 2018-10-18 20:35

from django.db import migrations, models
import django.utils.timezone
import profiles.utils
import sitewide.storage.backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, help_text="User's email address", max_length=254, unique=True, verbose_name='Email')),
                ('is_superuser', models.BooleanField(default=False, help_text='Site superuser or admin', verbose_name='Superuser')),
                ('is_staff', models.BooleanField(default=False, help_text='Site staff', verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True, help_text='User is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('first_name', models.CharField(help_text="User's first name", max_length=60, null=True, verbose_name='First name')),
                ('last_name', models.CharField(help_text="User's last name", max_length=255, null=True, verbose_name='Last name')),
                ('is_verified', models.BooleanField(default=False, help_text='User is verified', verbose_name='Verfied')),
                ('photo', models.ImageField(blank=True, help_text='User photo or avatar', max_length=255, null=True, storage=sitewide.storage.backend.MediaFilesStorage(), upload_to=profiles.utils.uploadto_user_photo, verbose_name='Photo')),
                ('status', models.CharField(choices=[('new', 'USER.STATUS.NEW'), ('overdue', 'USER.STATUS.OVERDUE'), ('active', 'USER.STATUS.ACTIVE'), ('banned', 'USER.STATUS.BANNED'), ('suspended', 'USER.STATUS.SUSPENDED')], default='new', help_text="User's account status", max_length=60, verbose_name='Status')),
                ('language', models.CharField(default='en', help_text="User's language", max_length=40, verbose_name='Language')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'permissions': (('read_profile', 'Can read all data on any profile'), ('update_profile', 'Can update public data on any profile'), ('switch_profile', 'Can switch to any non-superuser profile')),
            },
        ),
    ]
