language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
services: postgresql
before_install:
- export DATABASE_URL=postgres://postgres@localhost:5432/travisci
- cp config/settings/local.dst config/settings/local.py
- sudo /etc/init.d/postgresql stop
- wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key
  add -
- sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main
  9.5" >> /etc/apt/sources.list.d/postgresql.list'
- sudo apt-get update
- sudo apt-get install postgresql-9.5
install:
- pip install -r requirements/local.txt
script:
- py.test --cov=./apps
after_success:
- coveralls
notifications:
  slack:
    secure: wfIglIP3OUeSmHzSrerJccchjDxV8syKMSsrPd5pCLeHux4SVwon0Vr2dRxLQVTsx/ALzBBappA5VoyxCyzy866wc7Cx2Q+arj1OBY0Etj7PZB3o/3djRuIGXdMIrtL9DIb/HRvuaF0V8sX4u5hQgLVmzP01YKfhszzkLxTIXYw=
