language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

services: postgresql

before_install:
  - export DATABASE_URL=postgres://postgres@localhost:5432/travisci
# command to install dependencies
install:
  - pip install -r requirements/local.txt
# command to run tests
script:
  - python manage.py test