language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

services: postgresql

before_install:
  - export DATABASE_URL=postgres://postgres@localhost:5432/travisci
  - cp config/settings/local.dst config/settings/local.py
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
# command to install dependencies
install:
  - pip install -r requirements/local.txt
# command to run tests
script:
  - py.test --cov=./apps

afer_success:
  - coveralls