#!/bin/bash

type pycodestyle >/dev/null 2>&1 || {
  echo -e >&2 "Error: pycodestyle is not installed. Aborting\nRun (pip install pycodestyle)"; exit 1;
}

# Ignoring autogenerated files
#  -- Migration directories
# Ignoring error codes
#  -- E124 closing bracket does not match visual indentation
#  -- E125 continuation line under-indented for visual indent for params
#  -- E128 continuation line under-indented for visual indent
#  -- E225 missing whitespace around operator
#  -- E402 module level import not at top of file
#  -- E501 line too long
#  -- E731 avoid lambda and use def

pycodestyle --exclude=migrations --ignore=E124,E125,E128,E225,E402,E501,E731 .
