# Generated by Django 2.1.2 on 2019-04-09 19:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('label_en', models.CharField(max_length=255, null=True)),
                ('label_de', models.CharField(max_length=255, null=True)),
                ('summary', models.TextField()),
                ('summary_en', models.TextField(null=True)),
                ('summary_de', models.TextField(null=True)),
                ('pid', models.CharField(help_text="Do not use -'s or spaces in the pid.", max_length=255)),
                ('attribution', models.CharField(help_text='Repository holding the collection. List multiple if the manifests are from multiple collections.', max_length=255, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('upload', models.FileField(null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
