# Generated by Django 2.1.2 on 2018-11-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='pid',
            field=models.CharField(default='african-american-literature', max_length=255),
            preserve_default=False,
        ),
    ]
