# Generated by Django 2.1.2 on 2019-04-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0002_auto_20190410_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_image_creator',
            field=models.CharField(blank=True, help_text='The artist or author of the header/thumbnail image source.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_image_summary',
            field=models.CharField(blank=True, help_text='Any additional information to display about the header/thumbnail image source.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_image_title',
            field=models.CharField(blank=True, help_text='The title of the header/thumbnail image.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='header',
            field=models.ImageField(blank=True, help_text='You do not need to upload this file.', null=True, upload_to='headers/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='original',
            field=models.ImageField(help_text='Upload the Original Image and the Thumbnail and Banner will be created automatically!', null=True, upload_to='originals/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='You do not need to upload this file.', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='label',
            field=models.CharField(help_text='Title of the collection.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='label_de',
            field=models.CharField(help_text='Title of the collection.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='label_en',
            field=models.CharField(help_text='Title of the collection.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='pid',
            field=models.CharField(help_text="Unique ID. Do not use -'s or spaces in the pid.", max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='summary',
            field=models.TextField(help_text='Description of the collection.'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='summary_de',
            field=models.TextField(help_text='Description of the collection.', null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='summary_en',
            field=models.TextField(help_text='Description of the collection.', null=True),
        ),
    ]
