# Generated by Django 2.1.2 on 2019-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0003_auto_20190415_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
