# Generated by Django 2.2.10 on 2020-05-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0005_collection_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='original',
            field=models.ImageField(blank=True, help_text='Upload here to create the Thumbnail and Banner automatically for Collections pages!', null=True, upload_to='originals/'),
        ),
    ]
