# Generated by Django 2.2.24 on 2022-01-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0011_auto_20211028_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='header',
            field=models.ImageField(blank=True, help_text='Upload the image for the collection header here. Ideal ration 1200 x 300 px.', null=True, upload_to='headers/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='original',
            field=models.ImageField(blank=True, help_text='No longer used!', null=True, upload_to='originals/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='pid',
            field=models.CharField(default='2qt0qzj8', help_text="Unique ID. Do not use _'s or spaces in the pid.", max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload the image for the collection thumbnail here. Ideal ration 400 x 500 px.', null=True, upload_to='thumbnails/'),
        ),
    ]
