# Generated by Django 2.2.24 on 2022-01-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0012_auto_20220112_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_image_creator',
            field=models.CharField(blank=True, help_text='The artist or author of the header image source.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_image_summary',
            field=models.CharField(blank=True, help_text='Any additional information to display about the header image source.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_image_title',
            field=models.CharField(blank=True, help_text='The title of the header image.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='header',
            field=models.ImageField(help_text='Upload the image for the collection header here. Ideal ratio 1200 x 300 px.', null=True, upload_to='headers/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='pid',
            field=models.CharField(default='2r0m5dfj', help_text="Unique ID. Do not use _'s or spaces in the pid.", max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(help_text='Upload the image for the collection thumbnail here. Ideal ratio 400 x 500 px.', null=True, upload_to='thumbnails/'),
        ),
    ]
