# Generated by Django 2.2.24 on 2022-03-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0015_auto_20220203_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='pid',
            field=models.CharField(default='2r83gk66', help_text="Unique ID. Do not use _'s or spaces in the pid.", max_length=255),
        ),
    ]
