# Generated by Django 2.2.24 on 2022-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0019_auto_20220316_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='pid',
            field=models.CharField(default='2r7xbj80', help_text="Unique ID. Do not use _'s or spaces in the pid.", max_length=255),
        ),
    ]
