# Generated by Django 3.2.13 on 2022-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0022_alter_collection_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='label',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='label_de',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='label_en',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
