# Generated by Django 2.2.1 on 2019-07-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['order']},
        ),
    ]
