# Generated by Django 2.1.2 on 2019-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='motivation',
            field=models.CharField(choices=[('oa:commenting', 'commenting'), ('sc:painting', 'painting')], default='sc:painting', max_length=50),
        ),
    ]
