# Generated by Django 2.1.2 on 2019-07-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_auto_20190730_1620'),
        ('annotations', '0002_auto_20190715_2021'),
    ]

    operations = [
    ]
