# Generated by Django 2.1.2 on 2019-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_auto_20190822_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
