# Generated by Django 2.2.10 on 2021-02-22 20:39

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('annotations', '0006_auto_20201215_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['order'], 'permissions': (('view_user_annotation', 'View annotation'), ('admin_annotation', 'Manage annotation'))},
        ),
    ]
