# Generated by Django 2.2.10 on 2021-06-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_auto_20210309_1840'),
        ('annotations', '0007_auto_20210222_2039'),
    ]

    operations = [
    ]
