# Generated by Django 3.2.13 on 2022-06-07 14:07

from django.db import migrations, models

def assign_selector(app, _):
    """_summary_

    :param app: _description_
    :type app: _type_
    :param _: _description_
    :type _: _type_
    """
    # Annotation = apps.get_model("annotations", "Annotation")  # pylint: disable=invalid-name
    # for anno in Annotation.objects.all():
    #     anno.created_at = datetime.now()
    #     anno.updated_at = datetime.now()



class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_auto_20210309_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='primary_selector',
            field=models.CharField(choices=[('FR', 'FragmentSelector'), ('CS', 'CssSelector'), ('XP', 'XPathSelector'), ('TQ', 'TextQuoteSelector'), ('TP', 'TextPositionSelector'), ('DP', 'DataPositionSelector'), ('SV', 'SvgSelector'), ('RG', 'RangeSelector')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='annotation',
            name='purpose',
            field=models.CharField(choices=[('AS', 'assessing'), ('BM', 'bookmarking'), ('CL', 'classifying'), ('CM', 'commenting'), ('DS', 'describing'), ('ED', 'editing'), ('HL', 'highlighting'), ('ID', 'identifying'), ('LK', 'linking'), ('MO', 'moderating'), ('QT', 'questioning'), ('RE', 'replying'), ('TG', 'tagging')], default='CM', max_length=2),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='w',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(assign_selector, migrations.RunPython.noop),
  ]
