# Generated by Django 2.2.10 on 2021-06-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('guardian', '0002_generic_permissions_index'),
        ('users', '0003_auto_20200224_2038'),
        ('annotations', '0008_merge_20210618_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnotationGroup',
        ),
    ]
