# Generated by Django 4.2.30 on 2026-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0011_annotation_raw_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='motivation',
            field=models.CharField(choices=[('oa:commenting', 'commenting'), ('sc:painting', 'painting'), ('supplementing', 'supplementing')], default='sc:painting', max_length=50),
        ),
    ]
