# Generated by Django 2.1 on 2018-10-10 13:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('quote', models.TextField()),
                ('volume_identifier', models.TextField()),
                ('page', models.TextField()),
                ('uri', models.URLField()),
                ('volume_uri', models.URLField(blank=True)),
                ('iiif_annotation', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
