# Generated by Django 2.1 on 2018-08-22 18:40

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('quote', models.TextField()),
                ('uri', models.URLField()),
                ('volume_uri', models.URLField(blank=True)),
                ('iif_annotation', jsonfield.fields.JSONField(default='{}')),
            ],
        ),
    ]
