# Generated by Django 2.1 on 2018-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='volume_uri',
        ),
    ]
