# Generated by Django 2.1 on 2018-08-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_auto_20180823_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='page',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='volume_identifier',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
