# Generated by Django 2.1.2 on 2018-11-01 16:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kollections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('pdf', models.URLField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('viewingDirection', models.CharField(choices=[('left-to-right', 'Left to Right'), ('right-to-left', 'Right to Left')], default='left-to-right', max_length=13)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kollections.Collection')),
            ],
        ),
    ]
