# Generated by Django 2.1.2 on 2019-03-26 18:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kollections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('author', models.TextField(null=True)),
                ('published_city', models.TextField(null=True)),
                ('published_date', models.CharField(max_length=25)),
                ('publisher', models.CharField(max_length=255)),
                ('pdf', models.URLField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('viewingDirection', models.CharField(choices=[('left-to-right', 'Left to Right'), ('right-to-left', 'Right to Left')], default='left-to-right', max_length=13)),
                ('collections', models.ManyToManyField(related_name='manifests', to='kollections.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manifests.Manifest')),
            ],
        ),
    ]
