# Generated by Django 2.1.2 on 2019-07-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='rights',
            field=models.TextField(null=True),
        ),
    ]
