# Generated by Django 2.1.2 on 2018-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='pid',
            field=models.CharField(default='emory:b5h9g', max_length=255),
            preserve_default=False,
        ),
    ]
