# Generated by Django 2.1.2 on 2019-07-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0002_auto_20190730_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='attribution',
            field=models.CharField(blank=True, default='Emory University Libraries', help_text='The institution holding the manifest', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='license',
            field=models.CharField(blank=True, default='https://creativecommons.org/publicdomain/zero/1.0/', help_text='Only enter a URI to a license statement.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='logo',
            field=models.ImageField(blank=True, default='logos/lits-logo-web.png', help_text='Upload the Logo of the institution holding the manifest.', null=True, upload_to='logos/'),
        ),
    ]
