# Generated by Django 2.1.2 on 2019-11-15 15:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0004_auto_20190924_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
