# Generated by Django 2.1.2 on 2020-01-21 19:56

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0006_auto_20191217_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
