# Generated by Django 2.1.15 on 2020-02-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0007_auto_20200121_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='manifests', to='kollections.Collection'),
        ),
    ]
