# Generated by Django 2.2.10 on 2020-07-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0009_manifest_start_canvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='start_canvas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_canvas', to='canvases.Canvas'),
        ),
    ]
