# Generated by Django 2.1.2 on 2019-03-25 20:02
from __future__ import unicode_literals


from django.db import migrations, models


def make_many_collections(apps, schema_editor):
    """
        Adds the Collection object in Manifest.collection to the
        many-to-many relationship in Manifest.collections
    """
    Manifest = apps.get_model('manifests', 'Manifest')

    for manifest in Manifest.objects.all():
        manifest.collections.add(manifest.collection)


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0002_auto_20190320_1819'),
        ('manifests', '0011_auto_20190325_2002'),
    ]

    operations = [
        migrations.RunPython(make_many_collections),
    ]
