# Generated by Django 2.2.10 on 2021-01-06 16:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0012_auto_20200819_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='IServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('server_base', models.CharField(default='https://loris.library.emory.edu', max_length=255)),
                ('storage_service', models.CharField(choices=[('sftp', 'SFTP'), ('s3', 'S3')], default='sftp', max_length=10)),
                ('storage_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='manifest',
            name='image_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manifests.IServer'),
        ),
    ]
