# Generated by Django 2.1.2 on 2019-03-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0012_auto_20190325_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='collection',
        ),
    ]
