# Generated by Django 2.2.10 on 2021-01-08 19:59

from django.db import migrations

def forwards_func(apps, schema_editor):
    Manifest = apps.get_model('manifests', 'Manifest')
    ImageServer = apps.get_model('manifests', 'ImageServer')
    db_alias = schema_editor.connection.alias
    for manifest in Manifest.objects.using(db_alias).all():
        if manifest.canvas_set.first() is not None:
            canvas_i_server = manifest.canvas_set.first().IIIF_IMAGE_SERVER_BASE
            image_server, created = ImageServer.objects.get_or_create(server_base=canvas_i_server.IIIF_IMAGE_SERVER_BASE)
            if created:
                image_server.storage_service = canvas_i_server.storage_service
                image_server.storage_path = canvas_i_server.storage_path
                image_server.save()

def reverse_func(apps, schema_editor):
    Manifest = apps.get_model('manifests', 'Manifest')
    db_alias = schema_editor.connection.alias
    for manifest in Manifest.objects.using(db_alias).all():
        manifest.image_server.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0015_auto_20210108_1922'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
