# Generated by Django 2.2.10 on 2021-03-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0017_relatedlink_valuebylanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageserver',
            name='storage_service',
            field=models.CharField(choices=[('sftp', 'SFTP'), ('s3', 'S3'), ('remote', 'Remote')], default='sftp', max_length=10),
        ),
        migrations.AlterField(
            model_name='relatedlink',
            name='format',
            field=models.CharField(blank=True, choices=[('text/html', 'HTML'), ('application/json', 'JSON'), ('application/ld+json', 'JSON-LD'), ('application/xml', 'XML'), ('text/plan', 'Text')], max_length=255, null=True),
        ),
    ]
