# Generated by Django 2.2.23 on 2021-09-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0018_auto_20210309_1840'),
        ('manifests', '0010_auto_20200730_1549'),
    ]

    operations = [
    ]
