# Generated by Django 2.2.23 on 2021-09-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0019_merge_20210913_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='start_canvas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_canvas', to='canvases.Canvas'),
        ),
    ]
