# Generated by Django 2.2.24 on 2022-03-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0036_auto_20220203_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='pid',
            field=models.CharField(default='2r83gk66', help_text="Unique ID. Do not use _'s or spaces in the pid.", max_length=255),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='published_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='published_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
