# Generated by Django 2.2.24 on 2022-03-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0037_auto_20220316_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='author',
            field=models.TextField(blank=True, help_text='Enter multiple entities separated by a semicolon (;).', null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='pid',
            field=models.CharField(default='2r97h737', help_text="Unique ID. Do not use _'s or spaces in the pid.", max_length=255),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='published_city',
            field=models.TextField(blank=True, help_text='Enter multiple entities separated by a semicolon (;).', null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='publisher',
            field=models.TextField(blank=True, help_text='Enter multiple entities separated by a semicolon (;).', null=True),
        ),
    ]
