# Generated by Django 2.2.24 on 2022-03-16 16:11

from django.db import migrations, models
import edtf.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0040_auto_20220316_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='date_edtf',
            field=edtf.fields.EDTFField(blank=True, help_text="Use standard EDTF dates. For examples go to <a target='_blank' href='https://github.com/ixc/python-edtf#natural-language-representation'>https://github.com/ixc/python-edtf#natural-language-representation</a>", lower_fuzzy_field='date_earliest', lower_strict_field='date_sort_ascending', natural_text_field='published_date_edtf', null=True, upper_fuzzy_field='date_latest', upper_strict_field='date_sort_descending', verbose_name='Date of creation (EDTF)'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='pid',
            field=models.CharField(default='2r7xbj80', help_text="Unique ID. Do not use _'s or spaces in the pid.", max_length=255),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='published_date_edtf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
