# Generated by Django 3.2.12 on 2022-03-28 21:03

from django.db import migrations, models

from bcp47 import languages

def populate_languages(apps, schema_editor): # pylint: disable = unused-argument
    """Populate the new Language model with language codes/names"""
    Language = apps.get_model("manifests", "Language") # pylint: disable = invalid-name
    lang_list = []
    for label, code in languages.items():
        lang_list.append(Language(code=code, name=label))
    # for some reason Latin is not present in the library
    lang_list.append(Language(code="la", name="Latin"))
    Language.objects.bulk_create(lang_list)

class Migration(migrations.Migration):
    """Migration to create new Language model and populate it with language codes"""
    dependencies = [
        ("manifests", "0045_alter_valuebylanguage_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID")
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(populate_languages, migrations.RunPython.noop),
    ]
