# Generated by Django 3.2.12 on 2022-03-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0047_add_languages_to_manifest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='manifest',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Languages present in the manifest.', null=True, to='manifests.Language'),
        ),
    ]
