# Generated by Django 3.2.12 on 2022-04-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0045_auto_20220325_1328'),
        ('manifests', '0048_alter_languages_on_manifest'),
    ]

    operations = [
    ]
