# Generated by Django 3.2.12 on 2022-04-08 18:00

import edtf.fields
from edtf import parse_edtf, text_to_edtf, struct_time_to_jd, struct_time_to_date
from django.db import migrations, models
import apps.iiif.manifests.validators


def dates_to_edtf(apps, _):  # pylint: disable=redefined-outer-name
    """Migration function to attempt to convert all existing publication dates to EDTF dates."""
    Manifest = apps.get_model("manifests", "Manifest")  # pylint: disable=invalid-name
    manifests = Manifest.objects.filter(published_date__isnull=False).exclude(published_date="")
    for manifest in manifests:
        # handle some specific cases for data the EDTF library had trouble with
        if manifest.published_date in ["17th c.", "circa 17th century"]:
            edtf_standard_date = "1600~/1700~"
        elif manifest.published_date == "ca. 1820s–40s":
            edtf_standard_date = "1820~/1850~"
        else:
            edtf_standard_date = text_to_edtf(manifest.published_date)

        # store on the model if it was able to parse
        if edtf_standard_date:
            manifest.published_date_edtf = edtf_standard_date

            # normally, the following fields would all be set with a pre_save signal, but django
            # signals cannot be fired during migration, so we have to do it manually
            date_edtf = parse_edtf(edtf_standard_date)
            manifest.date_edtf = date_edtf
            manifest.date_earliest = struct_time_to_date(getattr(date_edtf, "lower_fuzzy")())
            manifest.date_latest = struct_time_to_date(getattr(date_edtf, "upper_fuzzy")())
            manifest.date_sort_ascending = struct_time_to_jd(getattr(date_edtf, "lower_strict")())
            manifest.date_sort_descending = struct_time_to_jd(getattr(date_edtf, "upper_strict")())
        else:
            print(f"""
            Failed to convert {manifest.published_date} to EDTF (manifest with pid {
                manifest.pid
            } and label {manifest.label}).""")

    Manifest.objects.bulk_update(manifests, [
        "published_date_edtf",
        "date_edtf",
        "date_earliest",
        "date_latest",
        "date_sort_ascending",
        "date_sort_descending",
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0049_merge_20220401_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='date_earliest',
        ),
        migrations.AddField(
            model_name='manifest',
            name='date_earliest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='date_latest',
        ),
        migrations.AddField(
            model_name='manifest',
            name='date_latest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='date_edtf',
            field=edtf.fields.EDTFField(
                blank=True,
                lower_fuzzy_field='date_earliest',
                lower_strict_field='date_sort_ascending',
                natural_text_field='published_date_edtf',
                null=True,
                upper_fuzzy_field='date_latest',
                upper_strict_field='date_sort_descending',
                verbose_name='Date of publication (EDTF)',
            ),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='published_date',
            field=models.CharField(
                blank=True,
                help_text='Used for display only.',
                max_length=255,
                null=True,
                verbose_name='Published date (display)',
            ),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='published_date_edtf',
            field=models.CharField(
                blank=True,
                help_text="Must be valid date conforming to the\n        <a href='https://www.loc.gov/standards/datetime/'>EDTF</a> standard. If left blank, volume\n        will be excluded from sorting and filtering by date of publication.",
                max_length=255,
                null=True,
                validators=[apps.iiif.manifests.validators.validate_edtf],
                verbose_name='Published date (EDTF)',
            ),
        ),
        migrations.RunPython(dates_to_edtf, migrations.RunPython.noop),
    ]
