# Generated by Django 3.2.13 on 2022-05-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0051_auto_20220503_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageserver',
            name='storage_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
