# Generated by Django 3.2.13 on 2022-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0052_alter_imageserver_storage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='label',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
