# Generated by Django 3.2.17 on 2023-02-16 20:43

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0053_auto_20220607_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL for thumbnail of holding institution's logo"),
        ),
        migrations.RunPython(
            migrations.RunPython.noop
        )
    ]
