# Generated by Django 3.2.12 on 2023-04-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0054_manifest_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='logo_url',
            field=models.URLField(blank=True, help_text='A URL in this field will take precedence over any logo file uploaded in the file field. Clear this field (if populated) to use an uploaded logo file instead.'),
        ),
    ]
