# Generated by Django 3.2.12 on 2023-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0055_alter_manifest_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageserver',
            name='requires_ptif',
            field=models.BooleanField(default=True),
        ),
    ]
