# Generated by Django 3.2.23 on 2025-01-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0058_alter_relatedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imageserver',
            name='storage_service',
            field=models.CharField(choices=[('sftp', 'SFTP'), ('s3', 'S3'), ('remote', 'Remote'), ('local', 'Local')], default='sftp', max_length=10),
        ),
    ]
