# Generated by Django 3.2.12 on 2023-12-05 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0058_alter_relatedlink_format_and_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedlink",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
