# Generated by Django 4.2.30 on 2026-05-13 14:18

from django.db import migrations
import edtf.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0059_auto_20250113_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='date_edtf',
            field=edtf.fields.EDTFField(blank=True, direct_input_field='published_date_edtf', lower_fuzzy_field='date_earliest', lower_strict_field='date_sort_ascending', natural_text_field='published_date_edtf', null=True, upper_fuzzy_field='date_latest', upper_strict_field='date_sort_descending', verbose_name='Date of publication (EDTF)'),
        ),
    ]
