# Generated by Django 3.2.12 on 2023-12-05 19:59

from django.db import migrations, models


def populate_is_structured_data(apps, schema_editor):
    # Data migration to populate RelatedLink.is_structured_data for existing data
    RelatedLink = apps.get_model("manifests", "RelatedLink")
    rl_set = RelatedLink.objects.all()
    for rl in rl_set:
        # Assume all existing RelatedLinks are structured data, since they were previously only
        # being added in Remote ingests when there was an existing manifest (which is structured
        # data)
        rl.is_structured_data = True
    RelatedLink.objects.bulk_update(rl_set, ["is_structured_data"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0059_alter_relatedlink_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedlink",
            name="is_structured_data",
            field=models.BooleanField(
                default=False,
                help_text="True if this link is structured data that should appear in the manifest's 'seeAlso' field; if false, the link will appear in the 'related' field instead. Leave unchecked if unsure.",
            ),
        ),
        migrations.AlterField(
            model_name="relatedlink",
            name="data_type",
            field=models.CharField(default="Dataset", max_length=255),
        ),
        migrations.RunPython(populate_is_structured_data, migrations.RunPython.noop),
    ]
