# Generated by Django 4.2.30 on 2026-05-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0060_alter_manifest_date_edtf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manifest",
            name="date_earliest",
        ),
        migrations.RemoveField(
            model_name="manifest",
            name="date_latest",
        ),
        migrations.AddField(
            model_name="manifest",
            name="date_earliest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manifest",
            name="date_latest",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
