# Generated by Django 5.2.14 on 2026-09-17 16:16

import apps.iiif.manifests.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0061_alter_manifest_date_earliest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='date_edtf',
            field=apps.iiif.manifests.fields.SafeEDTFField(blank=True, direct_input_field='published_date_edtf', lower_fuzzy_field='date_earliest', lower_strict_field='date_sort_ascending', natural_text_field='published_date_edtf', null=True, upper_fuzzy_field='date_latest', upper_strict_field='date_sort_descending', verbose_name='Date of publication (EDTF)'),
        ),
    ]
