# Generated by Django 2.1.15 on 2020-02-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='User Name to associate with Annotations', max_length=255, verbose_name='Name of User'),
        ),
    ]
