# Generated by Django 2.2.10 on 2020-04-24 19:27

from django.db import migrations

def create_initial_style(apps, schema_editor):
    Style = apps.get_model("custom_styles", "Style")
    initial_style = Style(
        primary_color='#FFFFFF',
        active=True
    )
    initial_style.save()

class Migration(migrations.Migration):

    dependencies = [
        ('custom_styles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_style)
    ]
