# Generated by Django 2.2.10 on 2020-04-24 19:27

from django.db import migrations
from ..tests.factories import StyleFactory

def create_initial_style(apps, schema_editor):
    StyleFactory.create(active=True)

class Migration(migrations.Migration):

    dependencies = [
        ('custom_styles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_style)
    ]
