# Generated by Django 2.2.23 on 2021-09-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_styles', '0003_auto_20200730_1549'),
        ('custom_styles', '0003_auto_20200730_1757'),
    ]

    operations = [
    ]
