# Generated by Django 2.1.2 on 2018-10-31 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identification', models.CharField(max_length=255, unique=True, verbose_name='COLLECTION.IDENTIFICATION')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='COLLECTION.LABEL')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='COLLECTION.SUMMARY')),
                ('attribution', models.TextField(blank=True, null=True, verbose_name='COLLECTION.ATTRIBUTION')),
            ],
            options={
                'verbose_name': 'COLLECTION.NAME.LABEL',
                'verbose_name_plural': 'COLLECTION.NAME.PLURAL',
            },
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('identification',)},
        ),
    ]
