# Generated by Django 2.1.2 on 2018-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(max_length=255, verbose_name='COLLECTION.CONTEXT')),
                ('identification', models.CharField(max_length=255, verbose_name='COLLECTION.IDENTIFICATION')),
                ('type', models.CharField(max_length=60, verbose_name='COLLECTION.TYPE')),
                ('label', models.CharField(max_length=255, verbose_name='COLLECTION.LABEL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='COLLECTION.DESCRIPTION')),
                ('attribution', models.TextField(blank=True, null=True, verbose_name='COLLECTION.ATTRIBUTION')),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='collection.Collection')),
            ],
            options={
                'verbose_name': 'COLLECTION.LABEL',
                'verbose_name_plural': 'COLLECTION.LABEL.PLURAL',
            },
        ),
    ]
