# Generated by Django 2.1.2 on 2018-10-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'COLLECTION.NAME.LABEL', 'verbose_name_plural': 'COLLECTION.NAME.PLURAL'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='identification',
            field=models.CharField(max_length=255, unique=True, verbose_name='COLLECTION.IDENTIFICATION'),
        ),
    ]
