# Generated by Django 2.1.2 on 2019-07-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('cms', '0001_squashed_0004_auto_20190409_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('page_title', models.TextField(blank=True)),
                ('tagline', models.TextField(blank=True)),
                ('paragraph', models.TextField(blank=True)),
                ('layout', models.CharField(choices=[('Grid', 'Grid'), ('List', 'List'), ('Banner', 'Banner')], default='List', help_text='Select to show all volumes as a list or a grid of icons.', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VolumesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('page_title', models.TextField(blank=True)),
                ('tagline', models.TextField(blank=True)),
                ('paragraph', models.TextField(blank=True)),
                ('layout', models.CharField(choices=[('Grid', 'Grid'), ('List', 'List')], default='Grid', help_text='Select to show all volumes as a list or a grid of icons.', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
