# Generated by Django 2.1.2 on 2019-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='custom_slug',
            field=models.TextField(blank=True),
        ),
    ]
