# Generated by Django 2.1.2 on 2019-03-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_contentpage_custom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='custom_slug',
        ),
    ]
