# Generated by Django 2.1.2 on 2020-01-28 17:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_collectionspage_volumespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='tagline',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
