# Generated by Django 3.2.23 on 2024-08-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0008_add_verbose_name_plural"),
        ("wagtailcore", "0083_workflowcontenttype"),
        ("wagtailmenus", "0023_remove_use_specific"),
        ("wagtailforms", "0005_alter_formsubmission_form_data"),
        ("cms", "0004_auto_20200224_2038"),
    ]

    operations = [
        migrations.DeleteModel(name="VolumesPage"),
    ]
