# Generated by Django 3.2.25 on 2024-09-19 20:35

from django.db import migrations


def create_footer_menu(apps, schema_editor):
    """
    Data migration to create a flat menu for the footer items.
    """
    Site = apps.get_model("wagtailcore", "Site")
    FlatMenu = apps.get_model("wagtailmenus", "FlatMenu")
    try:
        site = Site.objects.get(is_default_site=True)
    except Site.DoesNotExist:
        site = Site.objects.first()
    try:
        FlatMenu.objects.get(handle="footer-menu")
    except FlatMenu.DoesNotExist:
        FlatMenu.objects.create(
            title="Footer menu",
            handle="footer-menu",
            max_levels=1,
            site=site,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_homepage_featured_story"),
        ("wagtailmenus", "0023_remove_use_specific"),
    ]

    operations = [migrations.RunPython(create_footer_menu, migrations.RunPython.noop)]
