# Generated by Django 3.2.25 on 2024-09-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_create_footermenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="featured_video_tagline",
            field=models.CharField(
                blank=True,
                help_text="A short description or tagline for the featured video",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_video_title",
            field=models.CharField(
                blank=True, help_text="Title of the featured video", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_video_url",
            field=models.URLField(
                blank=True,
                help_text="Vimeo link to the featured video (e.g. https://vimeo.com/76979871, only Vimeo supported)",
            ),
        ),
    ]
