# Generated by Django 3.2.25 on 2024-10-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("cms", "0007_homepage_featured_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional background image for the site header",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
