from django.utils.translation import ugettext as _
from django.conf import settings

TESTWARE_EMAIL_DOMAIN_NAME = getattr(settings, "SITE_DOMAIN_NAME", "djangoware.org")
TESTWARE_TEMP_USER_PASS = 'changeme'
TESTWARE_LOREM_IPSUM = """Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor 
                   invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores"""

TESTWARE_USER_NAME_OPTIONS = (
    ("Aaron", _(u"Enlightened")),
    ("Abbott", _(u"Father")),
    ("Abel", _(u"Breath")),
    ("Abner", _(u"Father of Light")),
    ("Abraham", _(u"Exalted Father")),
    ("Adam", _(u"Man of Earth")),
    ("Addison", _(u"Son of Adam")),
    ("Adler", _(u"Eagle")),
    ("Adley", _(u"The Just")),
    ("Adrian Adrien", _(u"The Dark One")),
    ("Aedan Aiden", _(u"Born of Fire")),
    ("Aiken", _(u"The Oaken")),
    ("Alan Allan", _(u"Handsome One")),
    ("Alastair", _(u"Defender of Men")),
    ("Albern", _(u"Of Noble Valor")),
    ("Albert", _(u"Noble Bright")),
    ("Albion", _(u"White or Fair")),
    ("Alden", _(u"Wise Guardian")),
    ("Aldis", _(u"From the Old House")),
    ("Aldrich", _(u"Old Wise Leader")),
    ("Alexander", _(u"Great Protector")),
    ("Alfie", _(u"Form of Alfred")),
    ("Alfred", _(u"Supernaturally Wise")),
    ("Algernon", _(u"Bearded")),
    ("Alston", _(u"From the Old Manor")),
    ("Alton", _(u"From the Old Town")),
    ("Alvin", _(u"Noble Friend")),
    ("Ambrose", _(u"Immortal")),
    ("Amery", _(u"Industrious")),
    ("Amos", _(u"A Burden")),
    ("Andrew", _(u"Manly Valiant")),
    ("Angus", _(u"Strong and Unique")),
    ("Ansel", _(u"Nobel")),
    ("Anthony", _(u"Priceless")),
    ("Archer", _(u"Bowman")),
    ("Archibald", _(u"Bold Prince")),
    ("Arlen", _(u"Pledge")),
    ("Arnold", _(u"Strong as an Eagle")),
    ("Arthur Art", _(u"Champion Follower of Thor")),
    ("Arvel", _(u"Wept Over")),
    ("Atwater", _(u"From the Waterside")),
    ("Atwood", _(u"Forest Dweller")),
    ("Aubrey", _(u"Ruler of the Elves")),
    ("Austin", _(u"Helpful")),
    ("Avery", _(u"Elfin Ruler")),
    ("Axel", _(u"Man of Peace")),
    ("Baird", _(u"Bard or Minstrel")),
    ("Baldwin", _(u"Princely Friend")),
    ("Barclay", _(u"Meadow of Birch Trees")),
    ("Barnaby", _(u"Prophet")),
    ("Baron", _(u"Nobleman")),
    ("Barrett", _(u"Bear-Like")),
    ("Barry", _(u"Marksman")),
    ("Bartholomew", _(u"Warlike")),
    ("Basil", _(u"King-like")),
    ("Benedict", _(u"Blessed")),
    ("Benjamin", _(u"Son of Right Hand")),
    ("Benton", _(u"Moor Dweller")),
    ("Bernard", _(u"Stern Bear")),
    ("Bert", _(u"Bright")),
    ("Bevis", _(u"Bowman")),
    ("Blaine", _(u"Lean or Thin")),
    ("Blair", _(u"Man of Flatlands")),
    ("Blake", _(u"Fair Complexioned")),
    ("Bond", _(u"Farmer")),
    ("Boris", _(u"Warrior")),
    ("Bowen", _(u"Son of Owen")),
    ("Braden", _(u"From the Broad Valley")),
    ("Bradley", _(u"from the Broad Meadow")),
    ("Brandan Brendan Brendon", _(u"Traveller")),
    ("Brent", _(u"From the Steep Hill")),
    ("Bret Brett", _(u"Native of Brittany")),
    ("Brian", _(u"High Noble Strong")),
    ("Brice", _(u"Great Ambition")),
    ("Brigham", _(u"Dweller by the Bridge")),
    ("Brock", _(u"The Badger")),
    ("Broderick", _(u"Form of Roderick")),
    ("Brooke", _(u"A stream")),
    ("Bruce", _(u"Brushwood")),
    ("Bruno", _(u"Dark Complexioned")),
    ("Bryant", _(u"Strong")),
    ("Buck", _(u"The Deer")),
    ("Bud", _(u"Messenger")),
    ("Burgess", _(u"Citizen of a Town")),
    ("Burton", _(u"Fortress")),
    ("Byron", _(u"Bear")),
    ("Cadman", _(u"Warrior")),
    ("Calvert", _(u"Shepherd")),
    ("Caldwell", _(u"Near a Cold Well")),
    ("Caleb", _(u"Faithful")),
    ("Calvin", _(u"Bald")),
    ("Carrick", _(u"Rock")),
    ("Carl", _(u"Farmer")),
    ("Carlton", _(u"From Carl's Farm")),
    ("Carney", _(u"Warrior")),
    ("Carroll", _(u"Champion")),
    ("Carter", _(u"Cart Driver")),
    ("Carver", _(u"Wood Carver")),
    ("Cary", _(u"Fort")),
    ("Casey", _(u"Brave")),
    ("Casper", _(u"Treasure")),
    ("Cecil", _(u"Blind")),
    ("Cedric", _(u"Chieftain")),
    ("Chad Chadwick", _(u"Warrior")),
    ("Chalmers", _(u"Lord of the Household")),
    ("Chandler", _(u"Candlemaker")),
    ("Channing", _(u"A Canon")),
    ("Chapman", _(u"Merchant")),
    ("Charles", _(u"Manly")),
    ("Chatwin", _(u"Warlike Friend")),
    ("Chester", _(u"Castle Dweller")),
    ("Christian", _(u"A Christian")),
    ("Christopher", _(u"Christ-Bearer")),
    ("Clarence", _(u"Famous")),
    ("Claude", _(u"Lame")),
    ("Clayton Clay", _(u"The Clay Farm")),
    ("Clifford Cliff", _(u"Near the Cliff")),
    ("Clive", _(u"Cliff Dweller")),
    ("Clyde", _(u"Heard from Afar")),
    ("Coleman", _(u"Dove")),
    ("Colin", _(u"People's Victory")),
    ("Collier", _(u"Miner")),
    ("Conan", _(u"Wise")),
    ("Connell", _(u"Friendship")),
    ("Connor", _(u"Lover of Hounds")),
    ("Conrad", _(u"Able in Counsel")),
    ("Conroy", _(u"Wise Man")),
    ("Conway", _(u"Hound in the Plain")),
    ("Corwin", _(u"The Raven")),
    ("Crispin", _(u"Curly Haired")),
    ("Crosby", _(u"Dweller by Town Cross")),
    ("Culbert", _(u"Cool and Brilliant")),
    ("Culver", _(u"Dove")),
    ("Curt", _(u"Short or Little")),
    ("Curtis", _(u"Courteous")),
    ("Cuthbert", _(u"Famous and Brilliant")),
    ("Craig", _(u"Rocky Hill")),
    ("Cyril", _(u"Lord-like")),
    ("Dale Daley", _(u"Frequenter of Gatherings")),
    ("Dalton", _(u"Valley Estate")),
    ("Damon", _(u"Day of the Week")),
    ("Daniel", _(u"Ruler of the World")),
    ("Darcy", _(u"Dark")),
    ("Darian", _(u"Wealthy")),
    ("Darell Darrel", _(u"Beloved")),
    ("David", _(u"Swift Nimble Beloved")),
    ("Davin", _(u"Little Deer")),
    ("Dean", _(u"Great Leader")),
    ("Declan", _(u"Full of Goodness")),
    ("Delmar", _(u"Mariner")),
    ("Denley", _(u"From the Valley Meadow")),
    ("Dennis", _(u"Wild or Crazy")),
    ("Derek", _(u"Great Ruler")),
    ("Dermot", _(u"Without Enemy")),
    ("Derwin", _(u"Friend of Wild Animals")),
    ("Des Desmond", _(u"Like an Oak")),
    ("Dexter", _(u"Dexterous")),
    ("Dillon", _(u"Faithful")),
    ("Dion", _(u"Short for Dionysus")),
    ("Dirk", _(u"Ruler of People")),
    ("Dixon", _(u"Powerful Ruler")),
    ("Dominic", _(u"Belonging to the Lord")),
    ("Donald", _(u"Ruler")),
    ("Dorian", _(u"A Dorian")),
    ("Douglas", _(u"Dark")),
    ("Doyle", _(u"Stranger")),
    ("Drake", _(u"Dragon")),
    ("Drew", _(u"Trustworthy")),
    ("Driscoll", _(u"Interpreter")),
    ("Dudley", _(u"Residence Name")),
    ("Duncan", _(u"Dark Skinned Warrior")),
    ("Durwin", _(u"Beloved Friend")),
    ("Dwayne", _(u"Field or Meadow")),
    ("Dwight", _(u"White or Fair")),
    ("Dylan", _(u"Faithful Loyal")),
    ("Earl", _(u"Nobleman")),
    ("Eaton", _(u"From the Riverside")),
    ("Ebenezer", _(u"Rock of Help")),
    ("Edan", _(u"Fiery Flame")),
    ("Edgar", _(u"Fortunate Spear")),
    ("Edric", _(u"Prosperous Ruler")),
    ("Edmond Edmund", _(u"Guardian of the Riches")),
    ("Edward Eddie", _(u"Happy Protector")),
    ("Edwin", _(u"Valuable Friend")),
    ("Efrain", _(u"Guardian of the Mists")),
    ("Egan", _(u"Ardent")),
    ("Egbert", _(u"Formidably Brilliant")),
    ("Egerton", _(u"The Edge")),
    ("Egil", _(u"A Sting")),
    ("Elbert", _(u"Nobly Brilliant")),
    ("Eldon", _(u"Respected")),
    ("Eldwin", _(u"Sage Friend")),
    ("Eli Ely Elijah", _(u"The Highest")),
    ("Elias", _(u"Jehovah is God")),
    ("Eliot Elliott", _(u"Close to God")),
    ("Ellery", _(u"Cheerful")),
    ("Elmer", _(u"Awe-Inspiring")),
    ("Elroy", _(u"Royal")),
    ("Elton", _(u"Residence Name")),
    ("Elvis", _(u"A Wise and Noble Friend")),
    ("Emerson Emery", _(u"Industrious")),
    ("Emmanuel", _(u"God-like")),
    ("Emmett", _(u"Hard Working")),
    ("Emrick", _(u"Immortal")),
    ("Enoch", _(u"Dedicated or Consecrated")),
    ("Eric Erik", _(u"Honourable and Powerful")),
    ("Ernest", _(u"Iron Man Vigour")),
    ("Errol", _(u"Wanderering Noble")),
    ("Erskine", _(u"Hill Dweller")),
    ("Erwin", _(u"Friend of the Sea")),
    ("Esmond", _(u"Protective Grace")),
    ("Ethan Ethanael", _(u"Constant Firm Strong")),
    ("Ethen", _(u"Endurance")),
    ("Eugene", _(u"Born of the Yew Tree")),
    ("Evan", _(u"Young Warrior")),
    ("Everett", _(u"Wild Boar")),
    ("Ezra", _(u"The Helper")),
    ("Fabian", _(u"Bean Farmer")),
    ("Fairfax", _(u"Fair Haired")),
    ("Falkner", _(u"Falcon Trainer")),
    ("Farley", _(u"Distant Meadow")),
    ("Farrell", _(u"Man of Valor")),
    ("Felix", _(u"Prosperous")),
    ("Fenton", _(u"From the Flat Lands")),
    ("Ferdinand", _(u"Adventurous in Life")),
    ("Fergal", _(u"Brave and Couragous")),
    ("Fergus Ferguson", _(u"Strong and Virile")),
    ("Ferris", _(u"Iron Worker")),
    ("Finbar", _(u"The Fair")),
    ("Fitzgerald", _(u"Son of Gerald")),
    ("Fleming", _(u"Originating from Flanders")),
    ("Fletcher", _(u"Arrow Maker")),
    ("Floyd", _(u"The Hollow")),
    ("Forbes", _(u"Prosperous")),
    ("Forrest", _(u"Woodsman")),
    ("Foster", _(u"Bird Catcher")),
    ("Fox", _(u"Cunning")),
    ("Francis", _(u"Free")),
    ("Frank", _(u"Free Man")),
    ("Frasier", _(u"Strawberry")),
    ("Frederick", _(u"Peaceful Ruler")),
    ("Freeman", _(u"A Freeman")),
    ("Gabriel", _(u"Man of God")),
    ("Gale", _(u"A Stranger")),
    ("Galvin", _(u"Sparrow")),
    ("Gardner", _(u"Gardener")),
    ("Garret", _(u"Spear Champion")),
    ("Garrick", _(u"Spear King")),
    ("Garth", _(u"Herdsman")),
    ("Gavin", _(u"White Hawk")),
    ("George", _(u"Farmer")),
    ("Gerald Gerard Gerret", _(u"Spear Carrier")),
    ("Gideon", _(u"Great Warrior")),
    ("Gifford", _(u"Gift-Brave")),
    ("Gilbert", _(u"Pledge")),
    ("Giles", _(u"Bearer of Shield")),
    ("Gilroy", _(u"Servant of the King")),
    ("Glenn", _(u"Valley")),
    ("Goddard", _(u"Divinely Firm")),
    ("Godfrey", _(u"God's Peace")),
    ("Godwin", _(u"Divine Friend")),
    ("Graham", _(u"Grey Home")),
    ("Grant", _(u"Great")),
    ("Grayson", _(u"Son of Bailiff")),
    ("Gregory", _(u"Watchful One")),
    ("Gresham", _(u"From the Grazing Land")),
    ("Griswald Griswold", _(u"Residence Name")),
    ("Grover", _(u"Dweller in the Grove")),
    ("Guy", _(u"Guide")),
    ("Hadden", _(u"From the Moor")),
    ("Hadley", _(u"Heath Covered Moorland")),
    ("Hadwin", _(u"Friend in War")),
    ("Hal", _(u"Variant of Henry")),
    ("Halbert", _(u"Bright Stone")),
    ("Halden", _(u"Half-Dane")),
    ("Hale", _(u"Robust")),
    ("Hall", _(u"From the Hall or Manor")),
    ("Halsey", _(u"Residence Name")),
    ("Hamlin", _(u"Ruler of the Home")),
    ("Hanley", _(u"From the High Meadow")),
    ("Hardy", _(u"Strong")),
    ("Harlan Harland", _(u"Meadow of the Hares")),
    ("Harley", _(u"Army Meadow")),
    ("Harold Harry", _(u"Power")),
    ("Harris Harrison", _(u"Son of Harold")),
    ("Hartley", _(u"Residence Name")),
    ("Heath Heathcliff", _(u"From Heath or Moorland")),
    ("Hector", _(u"Steadfast")),
    ("Henry", _(u"Ruler of the House")),
    ("Herbert", _(u"Bright Warrior")),
    ("Herman", _(u"Warrior")),
    ("Homer", _(u"A Pledge or Security")),
    ("Horace Horatio", _(u"Timekeeper")),
    ("Howard", _(u"Strong Minded")),
    ("Hubert", _(u"Bright Minded")),
    ("Hugh Hugo", _(u"Fire")),
    ("Humphrey", _(u"Supporter of Peace")),
    ("Hunter", _(u"Hunter")),
    ("Ian", _(u"God is Gracious")),
    ("Igor", _(u"Heroic Warrior")),
    ("Irvin Irving", _(u"Handsome")),
    ("Isaac", _(u"Laughter")),
    ("Isaiah", _(u"God's Salvation")),
    ("Ivan", _(u"Form of John")),
    ("Iver Ivar", _(u"Archer")),
    ("Ives", _(u"Little Archer")),
    ("Jack", _(u"Godly")),
    ("Jacob", _(u"Conqueror")),
    ("James Jimmy", _(u"Supplanter")),
    ("Jarvis", _(u"Accurate Arrow")),
    ("Jason", _(u"God is my Saviour")),
    ("Jasper", _(u"Bearer of Treasure")),
    ("Jed", _(u"Beloved of the Lord")),
    ("Jeffrey", _(u"Peace Bringer")),
    ("Jeremiah Jeremy", _(u"Exalted")),
    ("Jerome", _(u"Of Sacred Name")),
    ("Jesse", _(u"Gift Giver")),
    ("John", _(u"God is Gracious")),
    ("Jonathan", _(u"A Gift")),
    ("Joseph Joey Joe", _(u"God Multiplies")),
    ("Joshua", _(u"God is my Salvation")),
    ("Justin", _(u"Just")),
    ("Kane", _(u"Honor")),
    ("Keene", _(u"Sharp")),
    ("Keegan", _(u"Fiery")),
    ("Keaton", _(u"Where Hawks Go")),
    ("Keith", _(u"Forest")),
    ("Kelsey", _(u"Island of Ships")),
    ("Kelvin", _(u"Friend of the Sea")),
    ("Kendall", _(u"Narrow River")),
    ("Kendrick", _(u"Ruler")),
    ("Kenneth Ken", _(u"Handsome")),
    ("Kent", _(u"Bright White")),
    ("Kenway", _(u"Courageous in Battle")),
    ("Kenyon", _(u"Blonde Haired")),
    ("Kerry", _(u"The Dark")),
    ("Kerwin", _(u"Dark Skinned")),
    ("Kevin", _(u"Handsome")),
    ("Kiefer", _(u"Barrel Maker")),
    ("Kilby", _(u"Residence Name")),
    ("Kilian", _(u"Blind")),
    ("Kim", _(u"Chief")),
    ("Kimball", _(u"Royally Brave")),
    ("Kingsley", _(u"Residence Name")),
    ("Kirby", _(u"Residence Name")),
    ("Kirk", _(u"Church")),
    ("Kit", _(u"The Christ-Bearer")),
    ("Kody", _(u"Helpful")),
    ("Konrad", _(u"Bold Speaker")),
    ("Kurt", _(u"Able in Counsel")),
    ("Kyle", _(u"Handsome")),
    ("Lambert", _(u"Land Bright")),
    ("Lamont", _(u"Lawyer")),
    ("Lancelot", _(u"Land")),
    ("Landon", _(u"Owner")),
    ("Landry", _(u"Ruler of the Place")),
    ("Lane", _(u"Narrow Road")),
    ("Lars", _(u"Variant of Lawrence")),
    ("Laurence", _(u"Bay or Laurel Tree")),
    ("Lee", _(u"Meadow")),
    ("Leith", _(u"Wide")),
    ("Leonard Leo Leon", _(u"Bold Lion")),
    ("Leroy", _(u"Powerful King")),
    ("Leslie", _(u"Residence Name")),
    ("Lester", _(u"Camp of the Legion")),
    ("Lincoln", _(u"Residence Name")),
    ("Lionel", _(u"Lion-like")),
    ("Lloyd", _(u"Grey")),
    ("Logan", _(u"Trench or Forest")),
    ("Lombard", _(u"Long-Beard")),
    ("Louis Lewis", _(u"Warrior")),
    ("Lowell", _(u"Beloved")),
    ("Lucas Luke", _(u"Luminous")),
    ("Luther", _(u"Warrior")),
    ("Lyndon", _(u"Linden Tree")),
    ("Maddox", _(u"Beneficient")),
    ("Magnus", _(u"Great")),
    ("Malcolm", _(u"Royal Blood")),
    ("Melvin", _(u"Servant")),
    ("Marcus", _(u"Warlike")),
    ("Mark Marc", _(u"Variant of Marcus")),
    ("Marlon", _(u"Falcon")),
    ("Martin", _(u"Warlike")),
    ("Marvin", _(u"Sea")),
    ("Matthew", _(u"Gift of the Lord")),
    ("Maurice", _(u"Dark Skin")),
    ("Max Maxwell", _(u"Great")),
    ("Medwin", _(u"Powerful Friend")),
    ("Melville", _(u"Form of Malvin")),
    ("Merlin", _(u"Bird")),
    ("Michael", _(u"Like God")),
    ("Milburn", _(u"Residence Name")),
    ("Miles", _(u"Soldier")),
    ("Monroe", _(u"A Wheeler")),
    ("Montague", _(u"Residence Name")),
    ("Montgomery", _(u"Mountain")),
    ("Morgan", _(u"From the Sea's Edge")),
    ("Morris", _(u"Moorish")),
    ("Morton", _(u"From the Farm or Moor")),
    ("Murray", _(u"Seaman")),
    ("Nathaniel Nathan", _(u"Gift of God")),
    ("Neal", _(u"Champion")),
    ("Neville", _(u"New Town")),
    ("Nicholas", _(u"People Triumph")),
    ("Nigel", _(u"Black")),
    ("Noel", _(u"To be Born")),
    ("Norman", _(u"Norseman")),
    ("Norris", _(u"Caretaker")),
    ("Olaf", _(u"Relic")),
    ("Olin", _(u"Holly")),
    ("Oliver", _(u"Olive Tree")),
    ("Orson", _(u"Like the Bear")),
    ("Oscar", _(u"Spear of God")),
    ("Oswald", _(u"Of God-Like Power")),
    ("Otis", _(u"Hears Well")),
    ("Owen", _(u"Well-Born")),
    ("Paul", _(u"Small")),
    ("Paxton", _(u"Travelling Trader")),
    ("Percival Percy", _(u"The Gorge Piercer")),
    ("Perry", _(u"Pear Tree")),
    ("Peter", _(u"Rock or Stone")),
    ("Peyton", _(u"Form of Patrick")),
    ("Philbert", _(u"Illustriously Brilliant")),
    ("Philip", _(u"Horse Lover")),
    ("Phineas", _(u"Brazen Mouth")),
    ("Pierce", _(u"Rock or Stone")),
    ("Quade", _(u"Fourth")),
    ("Quenby", _(u"Form of Quimby")),
    ("Quillan", _(u"Cub")),
    ("Quimby", _(u"Woman's Estate")),
    ("Quentin", _(u"Fifth Child")),
    ("Quinby", _(u"Residence Name")),
    ("Quincy", _(u"Residence Name")),
    ("Quinlan", _(u"Strong")),
    ("Quinn", _(u"The Wise")),
    ("Ralph", _(u"Variant of Randolph")),
    ("Ramsey", _(u"Island of Ravens")),
    ("Randolph", _(u"Strong Shield")),
    ("Raymond", _(u"Wise Guardian")),
    ("Reginald", _(u"Power")),
    ("Renfred", _(u"Peacemaker")),
    ("Rex", _(u"King")),
    ("Rhett", _(u"Stream")),
    ("Richard", _(u"Powerful Ruler")),
    ("Ridley", _(u"Residence Name")),
    ("Riley", _(u"Valiant")),
    ("Robert Robin", _(u"Bright Fame")),
    ("Roderick", _(u"Famous Ruler")),
    ("Rodney", _(u"Famous")),
    ("Roger", _(u"Famous Warrior")),
    ("Roland", _(u"Fame of the Land")),
    ("Rolf", _(u"Wolf")),
    ("Ronald", _(u"Of Mighty Power")),
    ("Rory", _(u"Red King")),
    ("Ross", _(u"Wood")),
    ("Roswell", _(u"Mighty Steed")),
    ("Roy", _(u"King")),
    ("Royce", _(u"Son of Roy Kingly")),
    ("Rufus", _(u"Red-Haired")),
    ("Rupert", _(u"Of Shining Fame")),
    ("Russell", _(u"Red")),
    ("Ryan", _(u"Variant of Bryan")),
    ("Samson", _(u"Bright as the Sun")),
    ("Samuel", _(u"Answer to Prayers")),
    ("Scott", _(u"From Scotland")),
    ("Sean", _(u"Heavenly Generosity")),
    ("Sebastian", _(u"Majestic")),
    ("Seth", _(u"Appointed One")),
    ("Seymour", _(u"Moorish Saint")),
    ("Shamus", _(u"Supplanter")),
    ("Shawn", _(u"God's Gracious Gift")),
    ("Shelley", _(u"Articulate")),
    ("Sherard", _(u"Of Splendid Valour")),
    ("Sheridan", _(u"The Wild Man")),
    ("Sherlock", _(u"Fair-Haired")),
    ("Sherman", _(u"Occupation Name")),
    ("Sherwin", _(u"A Friend")),
    ("Sidney", _(u"Earthy")),
    ("Sigmund", _(u"Victorious Protection")),
    ("Silas", _(u"Sound Forester")),
    ("Simon", _(u"A Visionary and Listener")),
    ("Sinclair", _(u"The Illustrious")),
    ("Sloane", _(u"Warrior")),
    ("Solomon", _(u"Peaceful")),
    ("Spencer", _(u"Steward")),
    ("Stanley Stan", _(u"Stony Field")),
    ("Stephen Stefan", _(u"Crown")),
    ("Sterling", _(u"High Quality")),
    ("Stewart Stuart", _(u"A Steward")),
    ("Theobold", _(u"Patriotic")),
    ("Theodore", _(u"Gift of God")),
    ("Thomas", _(u"Dependable")),
    ("Timothy", _(u"Honour God")),
    ("Titus", _(u"The Safe")),
    ("Tobias", _(u"Goodness of the Lord")),
    ("Toby", _(u"God is Good")),
    ("Todd", _(u"Fox")),
    ("Tony", _(u"Beyond Praise")),
    ("Travis Travers", _(u"At the Crossing")),
    ("Trent", _(u"Torrent")),
    ("Trevor", _(u"Great House")),
    ("Tristan", _(u"Sorrowful")),
    ("Troy", _(u"After the City")),
    ("Truman", _(u"A Faithful Loyal Man")),
    ("Tyler", _(u"Occupation Name")),
    ("Udolf", _(u"Prosperous Wolf")),
    ("Unwin", _(u"Nonfriend")),
    ("Uriah", _(u"God is my Light")),
    ("Vance", _(u"Thresher")),
    ("Vaughan", _(u"Small")),
    ("Vernon", _(u"Flourishing")),
    ("Victor", _(u"Conqueror")),
    ("Vincent", _(u"Victorious")),
    ("Wallace", _(u"Stranger")),
    ("Walter", _(u"Powerful Ruler")),
    ("Walton", _(u"Residence Name")),
    ("Ward", _(u"Guardian")),
    ("Warren", _(u"Protective Friend")),
    ("Washington", _(u"Residence Name")),
    ("Wayne", _(u"Wagon Maker")),
    ("Wesley", _(u"Man from the West")),
    ("Wilbur", _(u"Beloved Stronghold")),
    ("Willard", _(u"Great Bravery")),
    ("William Will", _(u"Determined Guardian")),
    ("Willis", _(u"Variant of Will")),
    ("Winston", _(u"Town of Victory")),
    ("Winthrop", _(u"Residence Name")),
    ("Wyatt", _(u"Guide")),
    ("Wylie", _(u"Beguiling")),
    ("Wyman", _(u"Warrior")),
    ("Zachariah", _(u"Remembered by the Lord")),
    ("Zachary", _(u"Remember the Lord")),
    ("Zebadiah", _(u"Gift of the Lord")),
    ("Zane", _(u"Form of John")),
    ("Zebediah", _(u"God's Gift")),
)

