# Generated by Django 2.2.10 on 2021-01-07 21:59

import apps.ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_squashed_0005_auto_20201027_1653'),
    ]

    operations = [

    ]
