# Generated by Django 2.2.10 on 2021-01-08 16:19

import apps.ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20210106_1658'),
    ]

    operations = [

    ]
