# Generated by Django 2.2.10 on 2020-10-27 14:52

import apps.ingest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0005_auto_20201027_1452'),
        ('ingest', '0002_auto_20201021_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='image_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvases.IServer'),
        )
    ]
