# Generated by Django 2.2.10 on 2021-01-08 19:22

import apps.ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_auto_20210108_1619'),
    ]

    operations = [

    ]
