# Generated by Django 2.2.10 on 2020-10-27 16:05

import apps.ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_auto_20201027_1452'),
    ]

    operations = [

    ]
