# Generated by Django 2.2.10 on 2020-10-27 16:53

import apps.ingest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0012_auto_20200819_1608'),
        ('ingest', '0004_auto_20201027_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='manifest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manifests.Manifest'),
        ),
        migrations.AlterField(
            model_name='local',
            name='image_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manifests.ImageServer'),
        )
    ]
