# Generated by Django 2.2.10 on 2021-01-19 19:36

import apps.ingest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_auto_20210108_1922'),
        ('manifests', '0015_auto_20210108_1922')
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='image_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manifests.ImageServer'),
        ),
    ]
