# Generated by Django 2.2.10 on 2021-01-22 16:46

import apps.ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_auto_20210119_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='temp_file_path',
            field=models.FilePathField(default=apps.ingest.models.make_temp_file, path='/tmp/tmpi8gubb4i'),
        ),
    ]
