# Generated by Django 2.2.10 on 2021-02-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_auto_20210122_1646'),
        ('ingest', '0002_auto_20210107_2159'),
    ]

    operations = [
    ]
