# Generated by Django 2.2.10 on 2021-03-09 18:40

import apps.ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_merge_20210208_2009'),
    ]

    operations = [

    ]
