# Generated by Django 2.2.10 on 2021-08-05 17:43

import apps.ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_auto_20210805_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BulkUploads',
            new_name='Volume',
        )
    ]
