# Generated by Django 2.2.10 on 2021-06-18 16:39

import apps.ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0012_auto_20210618_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='temp_file_path',
            field=models.FilePathField(default=apps.ingest.models.make_temp_file, path='/var/folders/6q/m6_cn6w96g158vldpfhnn6k40000gn/T/tmp98cne0je'),
        ),
    ]
