# Generated by Django 2.2.23 on 2021-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0018_auto_20210813_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='local_bundle_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
