# Generated by Django 2.2.23 on 2021-09-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0020_auto_20210915_1327'),
        ('ingest', '0019_auto_20210819_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulk',
            options={'verbose_name_plural': 'Bulk'},
        ),
        migrations.AddField(
            model_name='bulk',
            name='image_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manifests.ImageServer'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='bulk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.Bulk'),
        ),
    ]
