# Generated by Django 2.2.23 on 2021-09-15 14:33

import apps.ingest.models
import apps.ingest.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0020_auto_20210915_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='volume_files',
            field=models.FileField(default='test', storage=apps.ingest.storages.IngestStorage(), upload_to=apps.ingest.models.bulk_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
