# Generated by Django 2.2.23 on 2021-09-20 22:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0025_auto_20210920_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
