# Generated by Django 2.2.23 on 2021-09-28 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0012_remove_taskresult_task_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0027_remove_local_local_bundle_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestTaskWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, null=True)),
                ('task_id', models.CharField(max_length=255, null=True)),
                ('task_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('task_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.TaskResult')),
            ],
            options={
                'verbose_name_plural': 'IngestTaskWatcher',
            },
        ),
    ]
