# Generated by Django 2.2.23 on 2021-09-28 18:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0028_ingesttaskwatcher'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ingesttaskwatcher',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
