# Generated by Django 2.2.24 on 2021-10-07 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0029_auto_20210928_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingesttaskwatcher',
            options={'verbose_name_plural': 'Ingest Statuses'},
        ),
        migrations.AddField(
            model_name='local',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locals', to=settings.AUTH_USER_MODEL),
        ),
    ]
