# Generated by Django 2.2.24 on 2021-10-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0029_auto_20211012_1612'),
        ('ingest', '0030_auto_20211007_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingesttaskwatcher',
            name='associated_manifest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manifests.Manifest'),
        ),
    ]
