# Generated by Django 2.2.24 on 2021-10-28 15:27

import apps.ingest.models
import apps.ingest.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollections', '0011_auto_20211028_1527'),
        ('ingest', '0032_auto_20211026_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Optional: Collections to attach to ALL volumes ingested in this form.', null=True, to='kollections.Collection'),
        ),
        migrations.AddField(
            model_name='local',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Optional: Collections to attach to the volume ingested in this form.', null=True, to='kollections.Collection'),
        ),
        migrations.AlterField(
            model_name='local',
            name='bundle',
            field=models.FileField(blank=True, null=True, storage=apps.ingest.storages.IngestStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='local',
            name='bundle_from_bulk',
            field=models.FileField(blank=True, null=True, upload_to=apps.ingest.models.bulk_path),
        ),
    ]
