# Generated by Django 3.2.12 on 2023-04-20 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0035_s3ingest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s3ingest",
            name="metadata_spreadsheet",
            field=models.FileField(
                help_text="A spreadsheet file (CSV) with a row for each volume, including the\n        volume PID, which must match the subfolder name in the S3 bucket.",
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv"]
                    )
                ],
            ),
        ),
    ]
