# Generated by Django 3.2.12 on 2023-04-20 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0035_s3ingest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s3ingest",
            name="metadata_spreadsheet",
            field=models.FileField(
                help_text="A spreadsheet file (CSV) with a row for each volume, including the\n        volume PID (column name <strong>pid</strong>), which must match the subfolder name in the\n        S3 bucket.",
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="s3ingest",
            name="s3_bucket",
            field=models.CharField(
                help_text="The name of a publicly-accessible S3 bucket containing volumes to\n        ingest, either at the bucket root or within subfolder(s). Each volume should have its own\n        subfolder, with the volume's PID as its name.\n        <br />        \n        <strong>Example:</strong> if the bucket's URL is\n        https://my-bucket.s3.us-east-1.amazonaws.com/, its name is <strong>my-bucket</strong>.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="s3ingest",
            name="s3_prefix",
            field=models.CharField(
                blank=True,
                help_text="Optional: Subfolder(s) within the S3 bucket containing your volumes to ingest.\n        <br />\n        <strong>NOTE: If the volume PID subfolders are not at the bucket root, this field is\n        required.</strong>",
                max_length=255,
                null=True,
            ),
        ),
    ]
